### ISSUE TITLE
Mmap issue for Julia version > 0.6.1

### ISSUE THREAD

**Issue by dawnsong** [JuliaIO/NIfTI.jl#20]
Thanks for the NIfTI module.
For Julia v0.6.4, it is not compatible because of Mmap.
I think the code should be changed from

> if VERSION > v"0.6.1"
>     using **Mmap**
> end

to 

> if VERSION > v"0.6.1"
>     using **Base.Mmap**
> end

**Comment by Tokazama** [comment]
The current release doesn't have that line in it, nor does it support anything under v0.7.  I'm sure it would be possible to add support for older versions but I think that enough of the package ecosystem is starting to converge on v1+ that it may be better to update at this point. 

That being said, if you can't update for some reason you could always `Pkg.develop` an older release and implement the change yourself. See [this](https://docs.julialang.org/en/v1/stdlib/Pkg/#Using-someone-else's-project-1) for more details on this approach.

**Comment by dawnsong** [comment]
Thanks for the explanation. I am sticking to v0.6 since many packages are dependent on it.
I also look forward to all new updates, specially for the v1.0 releases.
