### ISSUE TITLE
Feature request: Reading and writing Bool datatype

### ISSUE THREAD

**Issue by korbinian90** [JuliaIO/NIfTI.jl#38]
Support for reading of the NIfTI datatype DT_BINARY and writing of AbstractArray{Bool} and BitArray is currently missing.

I added it (with tests) and will make a pull request.

Another question: Is there still work on a new version of NIfTI.jl? If so, it would be awesome if it would be publicly available for using, testing and improving it.

**Comment by Tokazama** [comment]
> Support for reading of the NIfTI datatype DT_BINARY and writing of AbstractArray{Bool} and BitArray is currently missing.
>
> I added it (with tests) and will make a pull request.

I tried to register a new release but there seems to be an error with the uuid. I'll look into this more.

> Another question: Is there still work on a new version of NIfTI.jl? If so, it would be awesome if it would be publicly available for using, testing and improving it.

If people would like me to I could update the branch but I have a lot of stuff that is hacky right now. I'm trying to complete the public API for AxisIndices.jl this week, which will finish the majority of work. Then I need to update NeuroCore.jl (which should be significantly simpler with AxisIndices.jl in place). Then the new version of NIfTI.jl will basically be ready to release. I anticipate it will be ready at the earliest in a couple weeks and at the latest a month (precluding more pandemics, lab shut downs, or major changes to my thesis project or committee).

**Comment by korbinian90** [comment]
Thank you for merging and for the status update on NIfTI.jl.
The plans for NIfTI.jl (with NeuroCore.jl and AxisIndices.jl) sound great!
